### ISSUE TITLE
ValueError: Digital filter critical frequencies must be 0 < Wn < 1

### ISSUE THREAD

**Issue by sainisanjay** [poganyg/IIR-filter#1]
@poganyg When sets the fs = 100 its raising `"ValueError: Digital filter critical frequencies must be 0 < Wn < 1"`
any idea??

**Comment by cubhe** [comment]
According to the Nyquist Theorem, the sampling rate must be more than twice the maximum frequency component of the signal being measured. Maybe you can change your frequencies to less than 100/2 :)

> @poganyg When sets the fs = 100 its raising `"ValueError: Digital filter critical frequencies must be 0 < Wn < 1"`
> any idea??

**Comment by poganyg** [comment]
Indeed @cubhe is correct, your sampling rate has to be LARGER than twice the maximum frequency in the signal you are measuring. The not-very-helpful error message has been discussed here:

https://github.com/scipy/scipy/issues/11235
